# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d82ced5ff14b6f96e2b9faa6310c6a668c3feb15e73c20b4640497042355963a67fa54c9289a88771822bfdf4d326d06552f70b2b80020ce8f7432e6d86c96

test:
  secret_key_base: 5b92c22b370b594e9dd2f37fe60c24ce4b767f2f39ff5c9231fd85f4babc18c40acc55f664bc523b155a1fe437bfe6c69dacda202f3428a518adaa92120fdaca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
